use crate::{Bool32, DeviceSize, SampleCountFlags, TRUE};

#[derive(Clone, Copy)]
pub struct PhysicalDeviceLimits {
    pub max_image_dimension1_d: u32,
    pub max_image_dimension2_d: u32,
    pub max_image_dimension3_d: u32,
    pub max_image_dimension_cube: u32,
    pub max_image_array_layers: u32,
    pub max_texel_buffer_elements: u32,
    pub max_uniform_buffer_range: u32,
    pub max_storage_buffer_range: u32,
    pub max_push_constants_size: u32,
    pub max_memory_allocation_count: u32,
    pub max_sampler_allocation_count: u32,
    pub buffer_image_granularity: DeviceSize,
    pub sparse_address_space_size: DeviceSize,
    pub max_bound_descriptor_sets: u32,
    pub max_per_stage_descriptor_samplers: u32,
    pub max_per_stage_descriptor_uniform_buffers: u32,
    pub max_per_stage_descriptor_storage_buffers: u32,
    pub max_per_stage_descriptor_sampled_images: u32,
    pub max_per_stage_descriptor_storage_images: u32,
    pub max_per_stage_descriptor_input_attachments: u32,
    pub max_per_stage_resources: u32,
    pub max_descriptor_set_samplers: u32,
    pub max_descriptor_set_uniform_buffers: u32,
    pub max_descriptor_set_uniform_buffers_dynamic: u32,
    pub max_descriptor_set_storage_buffers: u32,
    pub max_descriptor_set_storage_buffers_dynamic: u32,
    pub max_descriptor_set_sampled_images: u32,
    pub max_descriptor_set_storage_images: u32,
    pub max_descriptor_set_input_attachments: u32,
    pub max_vertex_input_attributes: u32,
    pub max_vertex_input_bindings: u32,
    pub max_vertex_input_attribute_offset: u32,
    pub max_vertex_input_binding_stride: u32,
    pub max_vertex_output_components: u32,
    pub max_tessellation_generation_level: u32,
    pub max_tessellation_patch_size: u32,
    pub max_tessellation_control_per_vertex_input_components: u32,
    pub max_tessellation_control_per_vertex_output_components: u32,
    pub max_tessellation_control_per_patch_output_components: u32,
    pub max_tessellation_control_total_output_components: u32,
    pub max_tessellation_evaluation_input_components: u32,
    pub max_tessellation_evaluation_output_components: u32,
    pub max_geometry_shader_invocations: u32,
    pub max_geometry_input_components: u32,
    pub max_geometry_output_components: u32,
    pub max_geometry_output_vertices: u32,
    pub max_geometry_total_output_components: u32,
    pub max_fragment_input_components: u32,
    pub max_fragment_output_attachments: u32,
    pub max_fragment_dual_source_attachments: u32,
    pub max_fragment_combined_output_resources: u32,
    pub max_compute_shared_memory_size: u32,
    pub max_compute_work_group_count: [u32; 3],
    pub max_compute_work_group_invocations: u32,
    pub max_compute_work_group_size: [u32; 3],
    pub sub_pixel_precision_bits: u32,
    pub sub_texel_precision_bits: u32,
    pub mipmap_precision_bits: u32,
    pub max_draw_index_value: u32,
    pub max_draw_indirect_count: u32,
    pub max_sampler_lod_bias: f32,
    pub max_sampler_anisotropy: f32,
    pub max_viewports: u32,
    pub max_viewport_dimensions: [u32; 2],
    pub viewport_bounds_range: [f32; 2],
    pub viewport_sub_pixel_bits: u32,
    pub min_memory_map_alignment: DeviceSize,
    pub min_texel_buffer_offset_alignment: DeviceSize,
    pub min_uniform_buffer_offset_alignment: DeviceSize,
    pub min_storage_buffer_offset_alignment: DeviceSize,
    pub min_texel_offset: i32,
    pub max_texel_offset: u32,
    pub min_texel_gather_offset: i32,
    pub max_texel_gather_offset: u32,
    pub min_interpolation_offset: f32,
    pub max_interpolation_offset: f32,
    pub sub_pixel_interpolation_offset_bits: u32,
    pub max_framebuffer_width: u32,
    pub max_framebuffer_height: u32,
    pub max_framebuffer_layers: u32,
    pub framebuffer_color_sample_counts: SampleCountFlags,
    pub framebuffer_depth_sample_counts: SampleCountFlags,
    pub framebuffer_stencil_sample_counts: SampleCountFlags,
    pub framebuffer_no_attachments_sample_counts: SampleCountFlags,
    pub max_color_attachments: u32,
    pub sampled_image_color_sample_counts: SampleCountFlags,
    pub sampled_image_integer_sample_counts: SampleCountFlags,
    pub sampled_image_depth_sample_counts: SampleCountFlags,
    pub sampled_image_stencil_sample_counts: SampleCountFlags,
    pub storage_image_sample_counts: SampleCountFlags,
    pub max_sample_mask_words: u32,
    pub timestamp_compute_and_graphics: bool,
    pub timestamp_period: f32,
    pub max_clip_distances: u32,
    pub max_cull_distances: u32,
    pub max_combined_clip_and_cull_distances: u32,
    pub discrete_queue_priorities: u32,
    pub point_size_range: [f32; 2],
    pub line_width_range: [f32; 2],
    pub point_size_granularity: f32,
    pub line_width_granularity: f32,
    pub strict_lines: bool,
    pub standard_sample_locations: bool,
    pub optimal_buffer_copy_offset_alignment: DeviceSize,
    pub optimal_buffer_copy_row_pitch_alignment: DeviceSize,
    pub non_coherent_atom_size: DeviceSize
}

#[repr(C)]
pub(crate) struct RawPhysicalDeviceLimits {
    max_image_dimension1_d: u32,
    max_image_dimension2_d: u32,
    max_image_dimension3_d: u32,
    max_image_dimension_cube: u32,
    max_image_array_layers: u32,
    max_texel_buffer_elements: u32,
    max_uniform_buffer_range: u32,
    max_storage_buffer_range: u32,
    max_push_constants_size: u32,
    max_memory_allocation_count: u32,
    max_sampler_allocation_count: u32,
    buffer_image_granularity: DeviceSize,
    sparse_address_space_size: DeviceSize,
    max_bound_descriptor_sets: u32,
    max_per_stage_descriptor_samplers: u32,
    max_per_stage_descriptor_uniform_buffers: u32,
    max_per_stage_descriptor_storage_buffers: u32,
    max_per_stage_descriptor_sampled_images: u32,
    max_per_stage_descriptor_storage_images: u32,
    max_per_stage_descriptor_input_attachments: u32,
    max_per_stage_resources: u32,
    max_descriptor_set_samplers: u32,
    max_descriptor_set_uniform_buffers: u32,
    max_descriptor_set_uniform_buffers_dynamic: u32,
    max_descriptor_set_storage_buffers: u32,
    max_descriptor_set_storage_buffers_dynamic: u32,
    max_descriptor_set_sampled_images: u32,
    max_descriptor_set_storage_images: u32,
    max_descriptor_set_input_attachments: u32,
    max_vertex_input_attributes: u32,
    max_vertex_input_bindings: u32,
    max_vertex_input_attribute_offset: u32,
    max_vertex_input_binding_stride: u32,
    max_vertex_output_components: u32,
    max_tessellation_generation_level: u32,
    max_tessellation_patch_size: u32,
    max_tessellation_control_per_vertex_input_components: u32,
    max_tessellation_control_per_vertex_output_components: u32,
    max_tessellation_control_per_patch_output_components: u32,
    max_tessellation_control_total_output_components: u32,
    max_tessellation_evaluation_input_components: u32,
    max_tessellation_evaluation_output_components: u32,
    max_geometry_shader_invocations: u32,
    max_geometry_input_components: u32,
    max_geometry_output_components: u32,
    max_geometry_output_vertices: u32,
    max_geometry_total_output_components: u32,
    max_fragment_input_components: u32,
    max_fragment_output_attachments: u32,
    max_fragment_dual_source_attachments: u32,
    max_fragment_combined_output_resources: u32,
    max_compute_shared_memory_size: u32,
    max_compute_work_group_count: [u32; 3],
    max_compute_work_group_invocations: u32,
    max_compute_work_group_size: [u32; 3],
    sub_pixel_precision_bits: u32,
    sub_texel_precision_bits: u32,
    mipmap_precision_bits: u32,
    max_draw_index_value: u32,
    max_draw_indirect_count: u32,
    max_sampler_lod_bias: f32,
    max_sampler_anisotropy: f32,
    max_viewports: u32,
    max_viewport_dimensions: [u32; 2],
    viewport_bounds_range: [f32; 2],
    viewport_sub_pixel_bits: u32,
    min_memory_map_alignment: DeviceSize,
    min_texel_buffer_offset_alignment: DeviceSize,
    min_uniform_buffer_offset_alignment: DeviceSize,
    min_storage_buffer_offset_alignment: DeviceSize,
    min_texel_offset: i32,
    max_texel_offset: u32,
    min_texel_gather_offset: i32,
    max_texel_gather_offset: u32,
    min_interpolation_offset: f32,
    max_interpolation_offset: f32,
    sub_pixel_interpolation_offset_bits: u32,
    max_framebuffer_width: u32,
    max_framebuffer_height: u32,
    max_framebuffer_layers: u32,
    framebuffer_color_sample_counts: SampleCountFlags,
    framebuffer_depth_sample_counts: SampleCountFlags,
    framebuffer_stencil_sample_counts: SampleCountFlags,
    framebuffer_no_attachments_sample_counts: SampleCountFlags,
    max_color_attachments: u32,
    sampled_image_color_sample_counts: SampleCountFlags,
    sampled_image_integer_sample_counts: SampleCountFlags,
    sampled_image_depth_sample_counts: SampleCountFlags,
    sampled_image_stencil_sample_counts: SampleCountFlags,
    storage_image_sample_counts: SampleCountFlags,
    max_sample_mask_words: u32,
    timestamp_compute_and_graphics: Bool32,
    timestamp_period: f32,
    max_clip_distances: u32,
    max_cull_distances: u32,
    max_combined_clip_and_cull_distances: u32,
    discrete_queue_priorities: u32,
    point_size_range: [f32; 2],
    line_width_range: [f32; 2],
    point_size_granularity: f32,
    line_width_granularity: f32,
    strict_lines: Bool32,
    standard_sample_locations: Bool32,
    optimal_buffer_copy_offset_alignment: DeviceSize,
    optimal_buffer_copy_row_pitch_alignment: DeviceSize,
    non_coherent_atom_size: DeviceSize,
}

impl PhysicalDeviceLimits {
    pub(crate) fn from_raw(raw: RawPhysicalDeviceLimits) -> PhysicalDeviceLimits {
        PhysicalDeviceLimits {
            max_image_dimension1_d: raw.max_image_dimension1_d,
            max_image_dimension2_d: raw.max_image_dimension2_d,
            max_image_dimension3_d: raw.max_image_dimension3_d,
            max_image_dimension_cube: raw.max_image_dimension_cube,
            max_image_array_layers: raw.max_image_array_layers,
            max_texel_buffer_elements: raw.max_texel_buffer_elements,
            max_uniform_buffer_range: raw.max_uniform_buffer_range,
            max_storage_buffer_range: raw.max_storage_buffer_range,
            max_push_constants_size: raw.max_push_constants_size,
            max_memory_allocation_count: raw.max_memory_allocation_count,
            max_sampler_allocation_count: raw.max_sampler_allocation_count,
            buffer_image_granularity: raw.buffer_image_granularity,
            sparse_address_space_size: raw.sparse_address_space_size,
            max_bound_descriptor_sets: raw.max_bound_descriptor_sets,
            max_per_stage_descriptor_samplers: raw.max_per_stage_descriptor_samplers,
            max_per_stage_descriptor_uniform_buffers: raw.max_per_stage_descriptor_uniform_buffers,
            max_per_stage_descriptor_storage_buffers: raw.max_per_stage_descriptor_storage_buffers,
            max_per_stage_descriptor_sampled_images: raw.max_per_stage_descriptor_sampled_images,
            max_per_stage_descriptor_storage_images: raw.max_per_stage_descriptor_storage_images,
            max_per_stage_descriptor_input_attachments: raw.max_per_stage_descriptor_input_attachments,
            max_per_stage_resources: raw.max_per_stage_resources,
            max_descriptor_set_samplers: raw.max_descriptor_set_samplers,
            max_descriptor_set_uniform_buffers: raw.max_descriptor_set_uniform_buffers,
            max_descriptor_set_uniform_buffers_dynamic: raw.max_descriptor_set_uniform_buffers_dynamic,
            max_descriptor_set_storage_buffers: raw.max_descriptor_set_storage_buffers,
            max_descriptor_set_storage_buffers_dynamic: raw.max_descriptor_set_storage_buffers_dynamic,
            max_descriptor_set_sampled_images: raw.max_descriptor_set_sampled_images,
            max_descriptor_set_storage_images: raw.max_descriptor_set_storage_images,
            max_descriptor_set_input_attachments: raw.max_descriptor_set_input_attachments,
            max_vertex_input_attributes: raw.max_vertex_input_attributes,
            max_vertex_input_bindings: raw.max_vertex_input_bindings,
            max_vertex_input_attribute_offset: raw.max_vertex_input_attribute_offset,
            max_vertex_input_binding_stride: raw.max_vertex_input_binding_stride,
            max_vertex_output_components: raw.max_vertex_output_components,
            max_tessellation_generation_level: raw.max_tessellation_generation_level,
            max_tessellation_patch_size: raw.max_tessellation_patch_size,
            max_tessellation_control_per_vertex_input_components: raw.max_tessellation_control_per_vertex_input_components,
            max_tessellation_control_per_vertex_output_components: raw.max_tessellation_control_per_vertex_output_components,
            max_tessellation_control_per_patch_output_components: raw.max_tessellation_control_per_patch_output_components,
            max_tessellation_control_total_output_components: raw.max_tessellation_control_total_output_components,
            max_tessellation_evaluation_input_components: raw.max_tessellation_evaluation_input_components,
            max_tessellation_evaluation_output_components: raw.max_tessellation_evaluation_output_components,
            max_geometry_shader_invocations: raw.max_geometry_shader_invocations,
            max_geometry_input_components: raw.max_geometry_input_components,
            max_geometry_output_components: raw.max_geometry_output_components,
            max_geometry_output_vertices: raw.max_geometry_output_vertices,
            max_geometry_total_output_components: raw.max_geometry_total_output_components,
            max_fragment_input_components: raw.max_fragment_input_components,
            max_fragment_output_attachments: raw.max_fragment_output_attachments,
            max_fragment_dual_source_attachments: raw.max_fragment_dual_source_attachments,
            max_fragment_combined_output_resources: raw.max_fragment_combined_output_resources,
            max_compute_shared_memory_size: raw.max_compute_shared_memory_size,
            max_compute_work_group_count: raw.max_compute_work_group_count,
            max_compute_work_group_invocations: raw.max_compute_work_group_invocations,
            max_compute_work_group_size: raw.max_compute_work_group_size,
            sub_pixel_precision_bits: raw.sub_pixel_precision_bits,
            sub_texel_precision_bits: raw.sub_texel_precision_bits,
            mipmap_precision_bits: raw.mipmap_precision_bits,
            max_draw_index_value: raw.max_draw_index_value,
            max_draw_indirect_count: raw.max_draw_indirect_count,
            max_sampler_lod_bias: raw.max_sampler_lod_bias,
            max_sampler_anisotropy: raw.max_sampler_anisotropy,
            max_viewports: raw.max_viewports,
            max_viewport_dimensions: raw.max_viewport_dimensions,
            viewport_bounds_range: raw.viewport_bounds_range,
            viewport_sub_pixel_bits: raw.viewport_sub_pixel_bits,
            min_memory_map_alignment: raw.min_memory_map_alignment,
            min_texel_buffer_offset_alignment: raw.min_texel_buffer_offset_alignment,
            min_uniform_buffer_offset_alignment: raw.min_uniform_buffer_offset_alignment,
            min_storage_buffer_offset_alignment: raw.min_storage_buffer_offset_alignment,
            min_texel_offset: raw.min_texel_offset,
            max_texel_offset: raw.max_texel_offset,
            min_texel_gather_offset: raw.min_texel_gather_offset,
            max_texel_gather_offset: raw.max_texel_gather_offset,
            min_interpolation_offset: raw.min_interpolation_offset,
            max_interpolation_offset: raw.max_interpolation_offset,
            sub_pixel_interpolation_offset_bits: raw.sub_pixel_interpolation_offset_bits,
            max_framebuffer_width: raw.max_framebuffer_width,
            max_framebuffer_height: raw.max_framebuffer_height,
            max_framebuffer_layers: raw.max_framebuffer_layers,
            framebuffer_color_sample_counts: raw.framebuffer_color_sample_counts,
            framebuffer_depth_sample_counts: raw.framebuffer_depth_sample_counts,
            framebuffer_stencil_sample_counts: raw.framebuffer_stencil_sample_counts,
            framebuffer_no_attachments_sample_counts: raw.framebuffer_no_attachments_sample_counts,
            max_color_attachments: raw.max_color_attachments,
            sampled_image_color_sample_counts: raw.sampled_image_color_sample_counts,
            sampled_image_integer_sample_counts: raw.sampled_image_integer_sample_counts,
            sampled_image_depth_sample_counts: raw.sampled_image_depth_sample_counts,
            sampled_image_stencil_sample_counts: raw.sampled_image_stencil_sample_counts,
            storage_image_sample_counts: raw.storage_image_sample_counts,
            max_sample_mask_words: raw.max_sample_mask_words,
            timestamp_compute_and_graphics: raw.timestamp_compute_and_graphics == TRUE,
            timestamp_period: raw.timestamp_period,
            max_clip_distances: raw.max_clip_distances,
            max_cull_distances: raw.max_cull_distances,
            max_combined_clip_and_cull_distances: raw.max_combined_clip_and_cull_distances,
            discrete_queue_priorities: raw.discrete_queue_priorities,
            point_size_range: raw.point_size_range,
            line_width_range: raw.line_width_range,
            point_size_granularity: raw.point_size_granularity,
            line_width_granularity: raw.line_width_granularity,
            strict_lines: raw.strict_lines == TRUE,
            standard_sample_locations: raw.standard_sample_locations == TRUE,
            optimal_buffer_copy_offset_alignment: raw.optimal_buffer_copy_offset_alignment,
            optimal_buffer_copy_row_pitch_alignment: raw.optimal_buffer_copy_row_pitch_alignment,
            non_coherent_atom_size: raw.non_coherent_atom_size

        }
    }
}