mod buffer;
mod buffer_view;
mod command_buffer;
mod command_pool;
mod descriptor_pool;
mod descriptor_set;
mod descriptor_set_layout;
mod device;
mod device_memory;
mod event;
mod fence;
mod framebuffer;
mod image;
mod image_view;
mod instance;
mod physical_device;
mod pipeline;
mod pipeline_cache;
mod pipeline_layout;
mod query_pool;
mod queue;
mod render_pass;
mod sampler;
mod semaphore;
mod shader_module;

pub use buffer::Buffer;
pub use buffer_view::BufferView;
pub use command_buffer::CommandBuffer;
pub use command_pool::CommandPool;
pub use descriptor_pool::DescriptorPool;
pub use descriptor_set::DescriptorSet;
pub use descriptor_set_layout::DescriptorSetLayout;
pub use device::Device;
pub use device_memory::DeviceMemory;
pub use event::Event;
pub use fence::Fence;
pub use framebuffer::Framebuffer;
pub use image::Image;
pub use image_view::ImageView;
pub use instance::Instance;
pub use physical_device::PhysicalDevice;
pub use pipeline::Pipeline;
pub use pipeline_cache::PipelineCache;
pub use pipeline_layout::PipelineLayout;
pub use query_pool::QueryPool;
pub use queue::Queue;
pub use render_pass::RenderPass;
pub use sampler::Sampler;
pub use semaphore::Semaphore;
pub use shader_module::ShaderModule;

use std::ffi::c_void;

type NonDispatchableHandle = u64;
type Handle = *mut c_void;